### ISSUE TITLE
[FR] Craft 4 Compatibility

### ISSUE THREAD

**Issue by kylecotter** [venveo/craft-redactor-split#4]
Any plans on upgrading this for Craft 4? It's proven to be a very helpful AX addition for a lot of our projects.

Thanks!

**Comment by maxfenton** [comment]
+1

**Comment by chadcrowell** [comment]
+1!

**Comment by Mosnar** [comment]
Thanks for your patience - just released 4.0.0 with Craft 4 support. Let me know if you have any issues!
